version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"   # expose cho host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: "host=db user=root password=secret dbname=mydb port=5432 sslmode=disable TimeZone=Asia/Ho_Chi_Minh"
      CLOUDINARY_CLOUD_NAME: "dtuffzxyb"
      CLOUDINARY_API_KEY: "343888939917252"
      CLOUDINARY_API_SECRET: "UtSWTZwBU55sz1f0teKW_QhZxXs"

volumes:
  postgres_data:
